hyperjob/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

from .views import IndexView
from .views import HomeView
from .views import LoginView
from .views import LogoutView
from .views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("", IndexView.as_view(), name="index"),

    path("home", HomeView.as_view(), name="home"),
    path("home/", RedirectView.as_view(url="/home")),

    path("login", LoginView.as_view(), name="login"),
    path("login/", RedirectView.as_view(url="/login")),

    path("logout", LogoutView.as_view(), name="logout"),
    path("logout/", RedirectView.as_view(url="/logout")),

    path("signup", SignupView.as_view(), name="signup"),
    path("signup/", RedirectView.as_view(url="/signup")),

    path("", include("resume.urls")),
    path("", include("vacancy.urls")),
]

urlpatterns += static(settings.STATIC_URL)

resume/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import NewResumeView
from .views import ResumesView

app_name = "resume"
urlpatterns = [
    path("resumes", ResumesView.as_view(), name="resumes"),
    path("resumes/", RedirectView.as_view(url="/resumes")),

    path("resume/new", NewResumeView.as_view(), name="new"),
    path("resume/new/", RedirectView.as_view(url="/resume/new")),
]

vacancy/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import NewVacancyView
from .views import VacancyView

app_name = "vacancy"
urlpatterns = [
    path("vacancies", VacancyView.as_view(), name="vacancies"),
    path("vacancies/", RedirectView.as_view(url="/vacancies")),

    path("vacancy/new", NewVacancyView.as_view(), name="new"),
    path("vacancy/new/", RedirectView.as_view(url="/vacancy/new")),
]

templates/create.html
{% extends "layout/base.html" %}

{% block content %}
    <h2>Add {% if vacancy_form %}Vacancy{% elif resume_form %}{% endif %}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% if vacancy_form %}
            {{ vacancy_form.as_p }}
        {% elif resume_form %}
            {{ resume_form.as_p }}
        {% endif %}
        <button type="submit">Add</button>
    </form>
{% endblock %}

templates/home.html
{% extends "layout/base.html" %}

{% block content %}
    <h2>Home</h2>
    {% if user.is_authenticated %}
        {% if user.is_staff %}
            <h3>Staff</h3>
            <form action="{% url 'vacancy:new' %}" method="get">
                {% csrf_token %}
                <button type="submit">Add Vacancy</button>
            </form>
            <br>
            {% for vacancy in vacancies %}
                <div>{{ vacancy.author.username }}: {{ vacancy.description }}</div>
            {% endfor %}
        {% else %}
            <h3>User</h3>
            <form action="{% url 'resume:new' %}" method="get">
                {% csrf_token %}
                <button type="submit">Add Resume</button>
            </form>
            <br>
            {% for resume in resumes %}
                <div>{{ resume.author.username }}: {{ resume.description }}</div>
            {% endfor %}
        {% endif %}
    {% else %}
        <p>Sign up if you would like to get the full experience.</p>
    {% endif %}
{% endblock %}

templates/index.html
{% extends "layout/base.html" %}

{% block content %}
    <h2>HyperJob Agency</h2>
{% endblock %}

templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}