hyperjob/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

from .views import IndexView
from .views import HomeView
from .views import LoginView
from .views import LogoutView
from .views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("", IndexView.as_view(), name="index"),

    path("home", HomeView.as_view(), name="home"),
    path("home/", RedirectView.as_view(url="/home")),

    path("login", LoginView.as_view(), name="login"),
    path("login/", RedirectView.as_view(url="/login")),

    path("logout", LogoutView.as_view(), name="logout"),
    path("logout/", RedirectView.as_view(url="/logout")),

    path("signup", SignupView.as_view(), name="signup"),
    path("signup/", RedirectView.as_view(url="/signup")),

    path("", include("resume.urls")),
    path("", include("vacancy.urls")),
]

urlpatterns += static(settings.STATIC_URL)

resume/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import NewResumeView
from .views import ResumesView

app_name = "resume"
urlpatterns = [
    path("resumes", ResumesView.as_view(), name="resumes"),
    path("resumes/", RedirectView.as_view(url="/resumes")),

    path("resume/new", NewResumeView.as_view(), name="new"),
    path("resume/new/", RedirectView.as_view(url="/resume/new")),
]

vacancy/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import NewVacancyView
from .views import VacancyView

app_name = "vacancy"
urlpatterns = [
    path("vacancies", VacancyView.as_view(), name="vacancies"),
    path("vacancies/", RedirectView.as_view(url="/vacancies")),

    path("vacancy/new", NewVacancyView.as_view(), name="new"),
    path("vacancy/new/", RedirectView.as_view(url="/vacancy/new")),
]

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% if title %}{{ title }}{% else %}HyperJob Agency{% endif %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

{% include "layout/header.html" %}

{% include "messages.html" %}

<main>
    {% block content %}{% endblock %}
</main>

{% include "layout/footer.html" %}

</body>
</html>

templates/layout/footer.html
<footer>
    <p>Made with &hearts; by Zane. Powered by Django.</p>
</footer>

templates/layout/header.html
<header>
    <h2>Welcome to HyperJob!</h2>
    <div><a href="{% url 'login' %}">Login</a></div>
    <div><a href="{% url 'signup' %}">Sign up</a></div>
    <div><a href="{% url 'vacancy:vacancies' %}">Vacancies</a></div>
    <div><a href="{% url 'resume:resumes' %}">Resumes</a></div>
    <div><a href="{% url 'home' %}">Home</a></div>
    {% if request.user.is_superuser or request.user == task.user %}
        <div>
            <a href="{% url 'admin:index' %}">Admin</a>
        </div>
    {% endif %}
    {% if user.is_authenticated %}
        <div>
            <a href="{% url 'logout' %}">Logout</a>
        </div>
    {% endif %}
</header>